version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: order_service_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"   # ⚠️ مختلف عن user_service
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - order_service_network

  # Go Web Service
  web:
    build: .
    container_name: order_service_web
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"   # Order Service port
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password123
      DB_NAME: order_service
      DB_SSLMODE: disable
    volumes:
      - .:/app
    networks:
      - order_service_network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - order_service_network

 

volumes:
  order_postgres_data:

networks:
  order_service_network:
    driver: bridge

